[package]
name = "simtest"
version = "0.1.0"
authors = ["Jon Lamb"]
edition = "2018"

[dependencies]
nphysics3d = "0.13"
nalgebra = "0.19"
kiss3d = "0.22"
ncollide3d = "0.21"
gilrs = "0.7"
pid = "2.0"
random_color = "0.4"
